### PR TITLE
Add real-life SPH benchmarks

### PR DESCRIPTION
**Pull request by efaulhaber**
Based on https://github.com/trixi-framework/TrixiParticles.jl/pull/550.

### CODE REVIEW

**Review by svchb — CHANGES_REQUESTED** [review]
This should be included in the benchmark testsuite?
Also do you want to add a file to actually run a benchmark?

**Comment by efaulhaber** [comment]
Thanks! Forgot to add it to the tests.

**Comment by efaulhaber** [comment]
Depends on https://github.com/trixi-framework/TrixiParticles.jl/pull/580.

**Review by svchb — APPROVED** [review]

**Comment by svchb** [comment]
@efaulhaber The tests still fail.

**Comment by efaulhaber** [comment]
Yes, waiting for the next release of TrixiParticles.

**Comment by efaulhaber** [comment]
The errors are fixed by https://github.com/trixi-framework/TrixiParticles.jl/pull/580.

**Review by svchb — APPROVED** [review]

**Review by LasNikas — APPROVED** [review]

**Pull request merged**
